//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApp.TutorWorldServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcWebApp.TutorWorldServiceRef.Student))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcWebApp.TutorWorldServiceRef.Teacher))]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonenumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phonenumber {
            get {
                return this.PhonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonenumberField, value) != true)) {
                    this.PhonenumberField = value;
                    this.RaisePropertyChanged("Phonenumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Student : MvcWebApp.TutorWorldServiceRef.UserProfile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.BookSession> BookSessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> TeachersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.BookSession> BookSessions {
            get {
                return this.BookSessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookSessionsField, value) != true)) {
                    this.BookSessionsField = value;
                    this.RaisePropertyChanged("BookSessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> Teachers {
            get {
                return this.TeachersField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachersField, value) != true)) {
                    this.TeachersField = value;
                    this.RaisePropertyChanged("Teachers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Teacher : MvcWebApp.TutorWorldServiceRef.UserProfile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> HourlyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Student> StudentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject> SubjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.WorkDay> WorkDaysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationLevel {
            get {
                return this.EducationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLevelField, value) != true)) {
                    this.EducationLevelField = value;
                    this.RaisePropertyChanged("EducationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> HourlyPrice {
            get {
                return this.HourlyPriceField;
            }
            set {
                if ((this.HourlyPriceField.Equals(value) != true)) {
                    this.HourlyPriceField = value;
                    this.RaisePropertyChanged("HourlyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((this.PostalCodeField.Equals(value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Student> Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject> Subjects {
            get {
                return this.SubjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectsField, value) != true)) {
                    this.SubjectsField = value;
                    this.RaisePropertyChanged("Subjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.WorkDay> WorkDays {
            get {
                return this.WorkDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkDaysField, value) != true)) {
                    this.WorkDaysField = value;
                    this.RaisePropertyChanged("WorkDays");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookSession", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BookSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.TimeSlot SlotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.TimeSlot Slot {
            get {
                return this.SlotField;
            }
            set {
                if ((object.ReferenceEquals(this.SlotField, value) != true)) {
                    this.SlotField = value;
                    this.RaisePropertyChanged("Slot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSlot", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TimeSlot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.BookSession> BookSessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.WorkDay WorkDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.BookSession> BookSessions {
            get {
                return this.BookSessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookSessionsField, value) != true)) {
                    this.BookSessionsField = value;
                    this.RaisePropertyChanged("BookSessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.WorkDay WorkDay {
            get {
                return this.WorkDayField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkDayField, value) != true)) {
                    this.WorkDayField = value;
                    this.RaisePropertyChanged("WorkDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Skill> SkillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Teacher TeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingsField, value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Skill> Skill {
            get {
                return this.SkillField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillField, value) != true)) {
                    this.SkillField = value;
                    this.RaisePropertyChanged("Skill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Teacher Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkDay", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WorkDay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DayOfWeek DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Teacher TeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.TimeSlot> TimeSlotsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Teacher Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.TimeSlot> TimeSlots {
            get {
                return this.TimeSlotsField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeSlotsField, value) != true)) {
                    this.TimeSlotsField = value;
                    this.RaisePropertyChanged("TimeSlots");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Rating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Skill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp.TutorWorldServiceRef.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillName {
            get {
                return this.SkillNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNameField, value) != true)) {
                    this.SkillNameField = value;
                    this.RaisePropertyChanged("SkillName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp.TutorWorldServiceRef.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class UserFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class SubjectError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class AuthFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TutorWorldServiceRef.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.UserFault), Action="http://tempuri.org/IUserService/UpdateUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void Update(MvcWebApp.TutorWorldServiceRef.UserProfile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(MvcWebApp.TutorWorldServiceRef.UserProfile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacherById", ReplyAction="http://tempuri.org/IUserService/FindTeacherByIdResponse")]
        MvcWebApp.TutorWorldServiceRef.Teacher FindTeacherById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacherById", ReplyAction="http://tempuri.org/IUserService/FindTeacherByIdResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Teacher> FindTeacherByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAuthenticatedTeacher", ReplyAction="http://tempuri.org/IUserService/GetAuthenticatedTeacherResponse")]
        MvcWebApp.TutorWorldServiceRef.Teacher GetAuthenticatedTeacher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAuthenticatedTeacher", ReplyAction="http://tempuri.org/IUserService/GetAuthenticatedTeacherResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Teacher> GetAuthenticatedTeacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacherList", ReplyAction="http://tempuri.org/IUserService/GetTeacherListResponse")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> GetTeacherList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacherList", ReplyAction="http://tempuri.org/IUserService/GetTeacherListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> GetTeacherListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAuthenticatedStudent", ReplyAction="http://tempuri.org/IUserService/GetAuthenticatedStudentResponse")]
        MvcWebApp.TutorWorldServiceRef.Student GetAuthenticatedStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAuthenticatedStudent", ReplyAction="http://tempuri.org/IUserService/GetAuthenticatedStudentResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Student> GetAuthenticatedStudentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateWorkDay", ReplyAction="http://tempuri.org/IUserService/CreateWorkDayResponse")]
        void CreateWorkDay(MvcWebApp.TutorWorldServiceRef.WorkDay workDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateWorkDay", ReplyAction="http://tempuri.org/IUserService/CreateWorkDayResponse")]
        System.Threading.Tasks.Task CreateWorkDayAsync(MvcWebApp.TutorWorldServiceRef.WorkDay workDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Book", ReplyAction="http://tempuri.org/IUserService/BookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IUserService/BookFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void Book(MvcWebApp.TutorWorldServiceRef.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Book", ReplyAction="http://tempuri.org/IUserService/BookResponse")]
        System.Threading.Tasks.Task BookAsync(MvcWebApp.TutorWorldServiceRef.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveBookedSession", ReplyAction="http://tempuri.org/IUserService/RemoveBookedSessionResponse")]
        void RemoveBookedSession(MvcWebApp.TutorWorldServiceRef.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveBookedSession", ReplyAction="http://tempuri.org/IUserService/RemoveBookedSessionResponse")]
        System.Threading.Tasks.Task RemoveBookedSessionAsync(MvcWebApp.TutorWorldServiceRef.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSubject", ReplyAction="http://tempuri.org/IUserService/AddSubjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.SubjectError), Action="http://tempuri.org/IUserService/AddSubjectSubjectErrorFault", Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        MvcWebApp.TutorWorldServiceRef.Subject AddSubject(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSubject", ReplyAction="http://tempuri.org/IUserService/AddSubjectResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Subject> AddSubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSkillset", ReplyAction="http://tempuri.org/IUserService/AddSkillsetResponse")]
        MvcWebApp.TutorWorldServiceRef.Skill AddSkillset(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSkillset", ReplyAction="http://tempuri.org/IUserService/AddSkillsetResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Skill> AddSkillsetAsync(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSkillset", ReplyAction="http://tempuri.org/IUserService/RemoveSkillsetResponse")]
        void RemoveSkillset(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSkillset", ReplyAction="http://tempuri.org/IUserService/RemoveSkillsetResponse")]
        System.Threading.Tasks.Task RemoveSkillsetAsync(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSubject", ReplyAction="http://tempuri.org/IUserService/RemoveSubjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.SubjectError), Action="http://tempuri.org/IUserService/RemoveSubjectSubjectErrorFault", Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void RemoveSubject(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSubject", ReplyAction="http://tempuri.org/IUserService/RemoveSubjectResponse")]
        System.Threading.Tasks.Task RemoveSubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateRating", ReplyAction="http://tempuri.org/IUserService/CreateRatingResponse")]
        MvcWebApp.TutorWorldServiceRef.Rating CreateRating(MvcWebApp.TutorWorldServiceRef.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateRating", ReplyAction="http://tempuri.org/IUserService/CreateRatingResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Rating> CreateRatingAsync(MvcWebApp.TutorWorldServiceRef.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRatingsBySubject", ReplyAction="http://tempuri.org/IUserService/GetRatingsBySubjectResponse")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating> GetRatingsBySubject(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRatingsBySubject", ReplyAction="http://tempuri.org/IUserService/GetRatingsBySubjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating>> GetRatingsBySubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetDistinctSubjets", ReplyAction="http://tempuri.org/IUserService/GetDistinctSubjetsResponse")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject> GetDistinctSubjets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetDistinctSubjets", ReplyAction="http://tempuri.org/IUserService/GetDistinctSubjetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject>> GetDistinctSubjetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterBySubject", ReplyAction="http://tempuri.org/IUserService/FilterBySubjectResponse")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterBySubject(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterBySubject", ReplyAction="http://tempuri.org/IUserService/FilterBySubjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterBySubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPrice", ReplyAction="http://tempuri.org/IUserService/FilterByPriceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.UserFault), Action="http://tempuri.org/IUserService/FilterByPriceUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterByPrice(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPrice", ReplyAction="http://tempuri.org/IUserService/FilterByPriceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterByPriceAsync(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPostalCode", ReplyAction="http://tempuri.org/IUserService/FilterByPostalCodeResponse")]
        System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterByPostalCode(int pc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPostalCode", ReplyAction="http://tempuri.org/IUserService/FilterByPostalCodeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterByPostalCodeAsync(int pc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindById", ReplyAction="http://tempuri.org/IUserService/FindByIdResponse")]
        MvcWebApp.TutorWorldServiceRef.Student FindById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindById", ReplyAction="http://tempuri.org/IUserService/FindByIdResponse")]
        System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Student> FindByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : MvcWebApp.TutorWorldServiceRef.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<MvcWebApp.TutorWorldServiceRef.IUserService>, MvcWebApp.TutorWorldServiceRef.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Update(MvcWebApp.TutorWorldServiceRef.UserProfile profile) {
            base.Channel.Update(profile);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(MvcWebApp.TutorWorldServiceRef.UserProfile profile) {
            return base.Channel.UpdateAsync(profile);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Teacher FindTeacherById(int id) {
            return base.Channel.FindTeacherById(id);
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Teacher> FindTeacherByIdAsync(int id) {
            return base.Channel.FindTeacherByIdAsync(id);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Teacher GetAuthenticatedTeacher() {
            return base.Channel.GetAuthenticatedTeacher();
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Teacher> GetAuthenticatedTeacherAsync() {
            return base.Channel.GetAuthenticatedTeacherAsync();
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> GetTeacherList() {
            return base.Channel.GetTeacherList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> GetTeacherListAsync() {
            return base.Channel.GetTeacherListAsync();
        }
        
        public MvcWebApp.TutorWorldServiceRef.Student GetAuthenticatedStudent() {
            return base.Channel.GetAuthenticatedStudent();
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Student> GetAuthenticatedStudentAsync() {
            return base.Channel.GetAuthenticatedStudentAsync();
        }
        
        public void CreateWorkDay(MvcWebApp.TutorWorldServiceRef.WorkDay workDay) {
            base.Channel.CreateWorkDay(workDay);
        }
        
        public System.Threading.Tasks.Task CreateWorkDayAsync(MvcWebApp.TutorWorldServiceRef.WorkDay workDay) {
            return base.Channel.CreateWorkDayAsync(workDay);
        }
        
        public void Book(MvcWebApp.TutorWorldServiceRef.BookSession session) {
            base.Channel.Book(session);
        }
        
        public System.Threading.Tasks.Task BookAsync(MvcWebApp.TutorWorldServiceRef.BookSession session) {
            return base.Channel.BookAsync(session);
        }
        
        public void RemoveBookedSession(MvcWebApp.TutorWorldServiceRef.BookSession session) {
            base.Channel.RemoveBookedSession(session);
        }
        
        public System.Threading.Tasks.Task RemoveBookedSessionAsync(MvcWebApp.TutorWorldServiceRef.BookSession session) {
            return base.Channel.RemoveBookedSessionAsync(session);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Subject AddSubject(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.AddSubject(subject);
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Subject> AddSubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.AddSubjectAsync(subject);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Skill AddSkillset(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.AddSkillset(skill, subject);
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Skill> AddSkillsetAsync(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.AddSkillsetAsync(skill, subject);
        }
        
        public void RemoveSkillset(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject) {
            base.Channel.RemoveSkillset(skill, subject);
        }
        
        public System.Threading.Tasks.Task RemoveSkillsetAsync(MvcWebApp.TutorWorldServiceRef.Skill skill, MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.RemoveSkillsetAsync(skill, subject);
        }
        
        public void RemoveSubject(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            base.Channel.RemoveSubject(subject);
        }
        
        public System.Threading.Tasks.Task RemoveSubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.RemoveSubjectAsync(subject);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Rating CreateRating(MvcWebApp.TutorWorldServiceRef.Rating rating) {
            return base.Channel.CreateRating(rating);
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Rating> CreateRatingAsync(MvcWebApp.TutorWorldServiceRef.Rating rating) {
            return base.Channel.CreateRatingAsync(rating);
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating> GetRatingsBySubject(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.GetRatingsBySubject(subject);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Rating>> GetRatingsBySubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.GetRatingsBySubjectAsync(subject);
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject> GetDistinctSubjets() {
            return base.Channel.GetDistinctSubjets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Subject>> GetDistinctSubjetsAsync() {
            return base.Channel.GetDistinctSubjetsAsync();
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterBySubject(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.FilterBySubject(subject);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterBySubjectAsync(MvcWebApp.TutorWorldServiceRef.Subject subject) {
            return base.Channel.FilterBySubjectAsync(subject);
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterByPrice(int min, int max) {
            return base.Channel.FilterByPrice(min, max);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterByPriceAsync(int min, int max) {
            return base.Channel.FilterByPriceAsync(min, max);
        }
        
        public System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher> FilterByPostalCode(int pc) {
            return base.Channel.FilterByPostalCode(pc);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MvcWebApp.TutorWorldServiceRef.Teacher>> FilterByPostalCodeAsync(int pc) {
            return base.Channel.FilterByPostalCodeAsync(pc);
        }
        
        public MvcWebApp.TutorWorldServiceRef.Student FindById(int id) {
            return base.Channel.FindById(id);
        }
        
        public System.Threading.Tasks.Task<MvcWebApp.TutorWorldServiceRef.Student> FindByIdAsync(int id) {
            return base.Channel.FindByIdAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TutorWorldServiceRef.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.AuthFault), Action="http://tempuri.org/IAuthService/LoginAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp.TutorWorldServiceRef.AuthFault), Action="http://tempuri.org/IAuthService/RegisterAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void Register(string email, string password, bool isTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string email, string password, bool isTeacher);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : MvcWebApp.TutorWorldServiceRef.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<MvcWebApp.TutorWorldServiceRef.IAuthService>, MvcWebApp.TutorWorldServiceRef.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login(string email, string password) {
            base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public void Register(string email, string password, bool isTeacher) {
            base.Channel.Register(email, password, isTeacher);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string email, string password, bool isTeacher) {
            return base.Channel.RegisterAsync(email, password, isTeacher);
        }
    }
}
