//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.TotorWorldService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.TotorWorldService.Student))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.TotorWorldService.Teacher))]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonenumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phonenumber {
            get {
                return this.PhonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonenumberField, value) != true)) {
                    this.PhonenumberField = value;
                    this.RaisePropertyChanged("Phonenumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Student : Client.TotorWorldService.UserProfile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.BookSession> BookSessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.Teacher> TeachersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.BookSession> BookSessions {
            get {
                return this.BookSessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookSessionsField, value) != true)) {
                    this.BookSessionsField = value;
                    this.RaisePropertyChanged("BookSessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.Teacher> Teachers {
            get {
                return this.TeachersField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachersField, value) != true)) {
                    this.TeachersField = value;
                    this.RaisePropertyChanged("Teachers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Teacher : Client.TotorWorldService.UserProfile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> HourlyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.Student> StudentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.Subject> SubjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.WorkDay> WorkDaysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationLevel {
            get {
                return this.EducationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLevelField, value) != true)) {
                    this.EducationLevelField = value;
                    this.RaisePropertyChanged("EducationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> HourlyPrice {
            get {
                return this.HourlyPriceField;
            }
            set {
                if ((this.HourlyPriceField.Equals(value) != true)) {
                    this.HourlyPriceField = value;
                    this.RaisePropertyChanged("HourlyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((this.PostalCodeField.Equals(value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.Student> Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.Subject> Subjects {
            get {
                return this.SubjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectsField, value) != true)) {
                    this.SubjectsField = value;
                    this.RaisePropertyChanged("Subjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.WorkDay> WorkDays {
            get {
                return this.WorkDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkDaysField, value) != true)) {
                    this.WorkDaysField = value;
                    this.RaisePropertyChanged("WorkDays");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookSession", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BookSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.TimeSlot SlotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.TimeSlot Slot {
            get {
                return this.SlotField;
            }
            set {
                if ((object.ReferenceEquals(this.SlotField, value) != true)) {
                    this.SlotField = value;
                    this.RaisePropertyChanged("Slot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSlot", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TimeSlot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.BookSession> BookSessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.WorkDay WorkDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.BookSession> BookSessions {
            get {
                return this.BookSessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookSessionsField, value) != true)) {
                    this.BookSessionsField = value;
                    this.RaisePropertyChanged("BookSessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.WorkDay WorkDay {
            get {
                return this.WorkDayField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkDayField, value) != true)) {
                    this.WorkDayField = value;
                    this.RaisePropertyChanged("WorkDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.Rating> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.Skill> SkillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Teacher TeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.Rating> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingsField, value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.Skill> Skill {
            get {
                return this.SkillField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillField, value) != true)) {
                    this.SkillField = value;
                    this.RaisePropertyChanged("Skill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Teacher Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkDay", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WorkDay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DayOfWeek DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Teacher TeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Client.TotorWorldService.TimeSlot> TimeSlotsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Teacher Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Client.TotorWorldService.TimeSlot> TimeSlots {
            get {
                return this.TimeSlotsField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeSlotsField, value) != true)) {
                    this.TimeSlotsField = value;
                    this.RaisePropertyChanged("TimeSlots");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Rating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Skill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TotorWorldService.Subject SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillName {
            get {
                return this.SkillNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNameField, value) != true)) {
                    this.SkillNameField = value;
                    this.RaisePropertyChanged("SkillName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TotorWorldService.Subject Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class UserFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class SubjectError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TotorWorldService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.TotorWorldService.UserFault), Action="http://tempuri.org/IUserService/UpdateUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void Update(Client.TotorWorldService.UserProfile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Client.TotorWorldService.UserProfile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacherById", ReplyAction="http://tempuri.org/IUserService/FindTeacherByIdResponse")]
        Client.TotorWorldService.Teacher FindTeacherById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacherById", ReplyAction="http://tempuri.org/IUserService/FindTeacherByIdResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Teacher> FindTeacherByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacher", ReplyAction="http://tempuri.org/IUserService/FindTeacherResponse")]
        Client.TotorWorldService.Teacher FindTeacher(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindTeacher", ReplyAction="http://tempuri.org/IUserService/FindTeacherResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Teacher> FindTeacherAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacherList", ReplyAction="http://tempuri.org/IUserService/GetTeacherListResponse")]
        System.Collections.Generic.List<Client.TotorWorldService.Teacher> GetTeacherList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacherList", ReplyAction="http://tempuri.org/IUserService/GetTeacherListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> GetTeacherListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindStudent", ReplyAction="http://tempuri.org/IUserService/FindStudentResponse")]
        Client.TotorWorldService.Student FindStudent(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindStudent", ReplyAction="http://tempuri.org/IUserService/FindStudentResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Student> FindStudentAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateWorkDay", ReplyAction="http://tempuri.org/IUserService/CreateWorkDayResponse")]
        void CreateWorkDay(Client.TotorWorldService.WorkDay workDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateWorkDay", ReplyAction="http://tempuri.org/IUserService/CreateWorkDayResponse")]
        System.Threading.Tasks.Task CreateWorkDayAsync(Client.TotorWorldService.WorkDay workDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Book", ReplyAction="http://tempuri.org/IUserService/BookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IUserService/BookFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void Book(Client.TotorWorldService.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Book", ReplyAction="http://tempuri.org/IUserService/BookResponse")]
        System.Threading.Tasks.Task BookAsync(Client.TotorWorldService.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveBookedSession", ReplyAction="http://tempuri.org/IUserService/RemoveBookedSessionResponse")]
        void RemoveBookedSession(Client.TotorWorldService.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveBookedSession", ReplyAction="http://tempuri.org/IUserService/RemoveBookedSessionResponse")]
        System.Threading.Tasks.Task RemoveBookedSessionAsync(Client.TotorWorldService.BookSession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSubject", ReplyAction="http://tempuri.org/IUserService/AddSubjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.TotorWorldService.SubjectError), Action="http://tempuri.org/IUserService/AddSubjectSubjectErrorFault", Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        Client.TotorWorldService.Subject AddSubject(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSubject", ReplyAction="http://tempuri.org/IUserService/AddSubjectResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Subject> AddSubjectAsync(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSkillset", ReplyAction="http://tempuri.org/IUserService/AddSkillsetResponse")]
        Client.TotorWorldService.Skill AddSkillset(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSkillset", ReplyAction="http://tempuri.org/IUserService/AddSkillsetResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Skill> AddSkillsetAsync(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSkillset", ReplyAction="http://tempuri.org/IUserService/RemoveSkillsetResponse")]
        void RemoveSkillset(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSkillset", ReplyAction="http://tempuri.org/IUserService/RemoveSkillsetResponse")]
        System.Threading.Tasks.Task RemoveSkillsetAsync(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSubject", ReplyAction="http://tempuri.org/IUserService/RemoveSubjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.TotorWorldService.SubjectError), Action="http://tempuri.org/IUserService/RemoveSubjectSubjectErrorFault", Name="SubjectError", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        void RemoveSubject(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSubject", ReplyAction="http://tempuri.org/IUserService/RemoveSubjectResponse")]
        System.Threading.Tasks.Task RemoveSubjectAsync(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateRating", ReplyAction="http://tempuri.org/IUserService/CreateRatingResponse")]
        Client.TotorWorldService.Rating CreateRating(Client.TotorWorldService.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateRating", ReplyAction="http://tempuri.org/IUserService/CreateRatingResponse")]
        System.Threading.Tasks.Task<Client.TotorWorldService.Rating> CreateRatingAsync(Client.TotorWorldService.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRatingsBySubject", ReplyAction="http://tempuri.org/IUserService/GetRatingsBySubjectResponse")]
        System.Collections.Generic.List<Client.TotorWorldService.Rating> GetRatingsBySubject(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetRatingsBySubject", ReplyAction="http://tempuri.org/IUserService/GetRatingsBySubjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Rating>> GetRatingsBySubjectAsync(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetDistinctSubjets", ReplyAction="http://tempuri.org/IUserService/GetDistinctSubjetsResponse")]
        System.Collections.Generic.List<Client.TotorWorldService.Subject> GetDistinctSubjets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetDistinctSubjets", ReplyAction="http://tempuri.org/IUserService/GetDistinctSubjetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Subject>> GetDistinctSubjetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterBySubject", ReplyAction="http://tempuri.org/IUserService/FilterBySubjectResponse")]
        System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterBySubject(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterBySubject", ReplyAction="http://tempuri.org/IUserService/FilterBySubjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterBySubjectAsync(Client.TotorWorldService.Subject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPrice", ReplyAction="http://tempuri.org/IUserService/FilterByPriceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.TotorWorldService.UserFault), Action="http://tempuri.org/IUserService/FilterByPriceUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
        System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterByPrice(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPrice", ReplyAction="http://tempuri.org/IUserService/FilterByPriceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterByPriceAsync(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPostalCode", ReplyAction="http://tempuri.org/IUserService/FilterByPostalCodeResponse")]
        System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterByPostalCode(int pc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FilterByPostalCode", ReplyAction="http://tempuri.org/IUserService/FilterByPostalCodeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterByPostalCodeAsync(int pc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Client.TotorWorldService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Client.TotorWorldService.IUserService>, Client.TotorWorldService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Update(Client.TotorWorldService.UserProfile profile) {
            base.Channel.Update(profile);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Client.TotorWorldService.UserProfile profile) {
            return base.Channel.UpdateAsync(profile);
        }
        
        public Client.TotorWorldService.Teacher FindTeacherById(int id) {
            return base.Channel.FindTeacherById(id);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Teacher> FindTeacherByIdAsync(int id) {
            return base.Channel.FindTeacherByIdAsync(id);
        }
        
        public Client.TotorWorldService.Teacher FindTeacher(string email, string password) {
            return base.Channel.FindTeacher(email, password);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Teacher> FindTeacherAsync(string email, string password) {
            return base.Channel.FindTeacherAsync(email, password);
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Teacher> GetTeacherList() {
            return base.Channel.GetTeacherList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> GetTeacherListAsync() {
            return base.Channel.GetTeacherListAsync();
        }
        
        public Client.TotorWorldService.Student FindStudent(string email, string password) {
            return base.Channel.FindStudent(email, password);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Student> FindStudentAsync(string email, string password) {
            return base.Channel.FindStudentAsync(email, password);
        }
        
        public void CreateWorkDay(Client.TotorWorldService.WorkDay workDay) {
            base.Channel.CreateWorkDay(workDay);
        }
        
        public System.Threading.Tasks.Task CreateWorkDayAsync(Client.TotorWorldService.WorkDay workDay) {
            return base.Channel.CreateWorkDayAsync(workDay);
        }
        
        public void Book(Client.TotorWorldService.BookSession session) {
            base.Channel.Book(session);
        }
        
        public System.Threading.Tasks.Task BookAsync(Client.TotorWorldService.BookSession session) {
            return base.Channel.BookAsync(session);
        }
        
        public void RemoveBookedSession(Client.TotorWorldService.BookSession session) {
            base.Channel.RemoveBookedSession(session);
        }
        
        public System.Threading.Tasks.Task RemoveBookedSessionAsync(Client.TotorWorldService.BookSession session) {
            return base.Channel.RemoveBookedSessionAsync(session);
        }
        
        public Client.TotorWorldService.Subject AddSubject(Client.TotorWorldService.Subject subject) {
            return base.Channel.AddSubject(subject);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Subject> AddSubjectAsync(Client.TotorWorldService.Subject subject) {
            return base.Channel.AddSubjectAsync(subject);
        }
        
        public Client.TotorWorldService.Skill AddSkillset(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject) {
            return base.Channel.AddSkillset(skill, subject);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Skill> AddSkillsetAsync(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject) {
            return base.Channel.AddSkillsetAsync(skill, subject);
        }
        
        public void RemoveSkillset(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject) {
            base.Channel.RemoveSkillset(skill, subject);
        }
        
        public System.Threading.Tasks.Task RemoveSkillsetAsync(Client.TotorWorldService.Skill skill, Client.TotorWorldService.Subject subject) {
            return base.Channel.RemoveSkillsetAsync(skill, subject);
        }
        
        public void RemoveSubject(Client.TotorWorldService.Subject subject) {
            base.Channel.RemoveSubject(subject);
        }
        
        public System.Threading.Tasks.Task RemoveSubjectAsync(Client.TotorWorldService.Subject subject) {
            return base.Channel.RemoveSubjectAsync(subject);
        }
        
        public Client.TotorWorldService.Rating CreateRating(Client.TotorWorldService.Rating rating) {
            return base.Channel.CreateRating(rating);
        }
        
        public System.Threading.Tasks.Task<Client.TotorWorldService.Rating> CreateRatingAsync(Client.TotorWorldService.Rating rating) {
            return base.Channel.CreateRatingAsync(rating);
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Rating> GetRatingsBySubject(Client.TotorWorldService.Subject subject) {
            return base.Channel.GetRatingsBySubject(subject);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Rating>> GetRatingsBySubjectAsync(Client.TotorWorldService.Subject subject) {
            return base.Channel.GetRatingsBySubjectAsync(subject);
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Subject> GetDistinctSubjets() {
            return base.Channel.GetDistinctSubjets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Subject>> GetDistinctSubjetsAsync() {
            return base.Channel.GetDistinctSubjetsAsync();
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterBySubject(Client.TotorWorldService.Subject subject) {
            return base.Channel.FilterBySubject(subject);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterBySubjectAsync(Client.TotorWorldService.Subject subject) {
            return base.Channel.FilterBySubjectAsync(subject);
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterByPrice(int min, int max) {
            return base.Channel.FilterByPrice(min, max);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterByPriceAsync(int min, int max) {
            return base.Channel.FilterByPriceAsync(min, max);
        }
        
        public System.Collections.Generic.List<Client.TotorWorldService.Teacher> FilterByPostalCode(int pc) {
            return base.Channel.FilterByPostalCode(pc);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.TotorWorldService.Teacher>> FilterByPostalCodeAsync(int pc) {
            return base.Channel.FilterByPostalCodeAsync(pc);
        }
    }
}
